### ISSUE TITLE
Where does a gene start and end?

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#102]
The genes rendered in the Gecko plot use the following method (where `start`, `end` and `exons` are fields in the `gecko()` API response):
* draw a line from `start` to `end`
* draw rectangles for each consecutive (start, end) pair in `exons`

This gives the following image for gene *MTERF1 (ENSG00000127989)*:
![Screen Shot 2018-09-07 at 10.08.47.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/5a9e10ea-e241-451a-b652-31e903f495cf)

However, the transcripts as they are rendered in Ensembl look like:
![Screen Shot 2018-09-07 at 10.26.11.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/c93309db-fae9-4fd3-b698-496b1711ed0a)

Where does a gene start and end? How should the genes in the Gecko plot be rendered?

**Comment by iandunham** [comment]
Have you looked at how thee paltform gets this information? e.g. the mini browser https://www.targetvalidation.org/target/ENSG00000127989

**Comment by iandunham** [comment]
Would be good to have the coordinates that the gecko api call is returning and the ensembl coordinates for comparison

**Comment by peatroot** [comment]
Thanks @iandunham. The mini-browser on the target profile page renders all transcripts for the given gene (and rectangles for the rest); see screenshot below.
<img width="1118" alt="screen shot 2018-09-10 at 16 52 48" src="https://user-images.githubusercontent.com/7376272/45309308-58998280-b51b-11e8-9b0a-f19789e52c30.png">


In the genetics platform, we planned to show just the canonical transcript (MTERF1's canonical is `ENST00000351870=MTERF1-201` as found [here](http://grch37.rest.ensembl.org/lookup/id/ENSG00000127989?content-type=application/json;expand=1)). The information we are using is the `gs://genetics-portal-data/lut/gene_dictionary.json` Eliseo and Ed have made. For each gene, it contains the tss, start, end, and exon positions for the **canonical** transcript only (generated using [this](https://github.com/opentargets/genetics-backend/blob/master/makeLUTs/create_genes_dictionary.py)).

The API currently returns the following:
```
{
    "id": "ENSG00000127989",
    "symbol": "MTERF",
    "start": 91321323,
    "end": 91510034,
    "tss": 91510034,
    "exons": [
        91509971,
        91510034,
        91509369,
        91509427,
        91502205,
        91504078
    ]
},
```
The `start` field is the start of the gene (where `MTERF1-206` begins), not where the canonical transcript (`MTERF1-201`) begins. However, the canonical transcript is much shorter, so I'm not sure which would make more sense to a user.

Any thoughts on this @iandunham @elipapa @edm1?

**Comment by peatroot** [comment]
If you want to reproduce the API response, you can query:
```
{
  gecko(chromosome:"7", start: 91600000, end: 91900000) {
    genes {
      id
      symbol
      start
      end
      tss
      exons
    }
  }
}
```

**Comment by iandunham** [comment]
I think the problem is that what you appear to be getting is the start of the "gene" which is built from the largest extent of all the transcripts, rather than the start of the canonical transcript in this case. You may need to check the code that builds you gene lut, as this example doesn't seem to be behaving as you anticipate

Going through the specific case on GRCh37 you need this section of the Ensembl API call for MTERF-003, and to get the start and end coordinates from the canonical transcript section. 


"Exon":
[
{
"assembly_name":
"GRCh37",
"db_type":
"core",
"end":
91510034,
"id":
"ENSE00001852655",
"object_type":
"Exon",
"seq_region_name":
"7",
"species":
"homo_sapiens",
"start":
91509971,
"strand":
-1,
"version":
1
},
{
"assembly_name":
"GRCh37",
"db_type":
"core",
"end":
91509427,
"id":
"ENSE00003666957",
"object_type":
"Exon",
"seq_region_name":
"7",
"species":
"homo_sapiens",
"start":
91509369,
"strand":
-1,
"version":
1
},
{
"assembly_name":
"GRCh37",
"db_type":
"core",
"end":
91504078,
"id":
"ENSE00001132795",
"object_type":
"Exon",
"seq_region_name":
"7",
"species":
"homo_sapiens",
"start":
91502205,
"strand":
-1,
"version":
3
}
],
"Parent":
"ENSG00000127989",
"Translation":
{
"Parent":
"ENST00000351870",
"db_type":
"core",
"end":
91509397,
"id":
"ENSP00000248643",
"length":
399,
"object_type":
"Translation",
"species":
"homo_sapiens",
"start":
91502908
},
"assembly_name":
"GRCh37",
"biotype":
"protein_coding",
"db_type":
"core",
"display_name":
"MTERF-003",
"end":
91510034,
"id":
"ENST00000351870",
"is_canonical":
1,
"logic_name":
"ensembl_havana_transcript",
"object_type":
"Transcript",
"seq_region_name":
"7",
"source":
"ensembl_havana",
"species":
"homo_sapiens",
"start":
91502205,
"strand":
-1,
"version":
3

which gives you 

Gene "start": 91502205,
Gene  "end": 91510034,

Exon "end": 91510034,
Exon "start": 91509971,
Exon "end": 91509427,
Exon "start": 91509369,
Exon  "end": 91504078,
Exon "start": 91502205,

and this will draw consistently.

Alternately you could grab all the exons of the canonical transcript and work out the range

**Comment by elipapa** [comment]
@iandunham is right: it looks as if the `gene.start` we pass you is generally different than the first exon of the canonical transcript. 


As you can see [in the code](https://github.com/opentargets/genetics-backend/blob/master/makeLUTs/create_genes_dictionary.py#L43) we pass you exons for the canonical transcript only, as [defined by ensembl in their glossary and in their API/SQL database](https://www.ensembl.org/Help/Glossary?id=346):

> the canonical transcript for a gene is set according to the following hierarchy: 1. Longest CCDS translation with no stop codons. 2. If no (1), choose the longest Ensembl/Havana merged translation with no stop codons. 3. If no (2), choose the longest translation with no stop codons. 4. If no translation, choose the longest non-protein-coding transcript.

**Comment by peatroot** [comment]
Yes, passing `transcript.start` and `transcript.end` would mean I show the canonical transcript accurately. The API probably doesn't need the gene's `start` and `end` fields at all.
