### ISSUE TITLE
Gecko plot - show all genes all the time

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#117]
We should show all genes in the gene track. Any that are part of the selection should be highlighted.

**Comment by elipapa** [comment]
👍 should we highlight the connected ones as well?
for eg. selecting FTO as a gene returns all the VT/VL/S connected to it. We should probably highlight the genes that share VT/VL with FTO (eg. IRX3/IRX5) ? 
I would find this very helpful to dissect the one-to-many assignments.

**Comment by MayaGhoussaini** [comment]
I should not be reading work-related stuff while on the beach but couldn’t help myself with this one.
I think if people click on FTO for example, I don’t see why the other genes connected to it such as IRX3/5 should get highlighted as well (even if they’re all being targeted by overlapping set of SNPs or make sense biologically speaking ). Only VT and VL and the studies in which they were reported should get highlighted. The question people are asking if they click on FTO is : what variants and phenotypes/studies are connected with this gene?  If they’re interested in seeing FTO, IRX3/5 highlighted at the same time as targets of lipid-related phenotypes, the starting point should be either the study/phenotype that connect the lead/tag variants in the region to these genes or the VT and VL that target those genes.



Sent from my iPhone

On 20 Sep 2018, at 13:46, elipapa <notifications@github.com<mailto:notifications@github.com>> wrote:


👍 should we highlight the connected ones as well?
for eg. selecting FTO as a gene returns all the VT/VL/S connected to it. We should probably highlight the genes that share VT/VL with FTO (eg. IRX3/IRX5) ?
I would find this very helpful to dissect the one-to-many assignments.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opentargets_genetics_issues_117-23issuecomment-2D423136762&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=Aush8haVNQv3Cbg5voWXggyiSQ8DTw3yQv8KnEt8Ne4&m=Q7bnh_9Hw2np3SlCGRJAKXpHFAAz0X8PzkCyefyQ6Go&s=xWW9bHTkt4MWMSbfvD_8agV5NX3j822m6gnEU2Wxtwc&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AahKyv3KICxn8LC0VeVvZGMQxsICWl-5FOks5uc3HogaJpZM4Wv4ap&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=Aush8haVNQv3Cbg5voWXggyiSQ8DTw3yQv8KnEt8Ne4&m=Q7bnh_9Hw2np3SlCGRJAKXpHFAAz0X8PzkCyefyQ6Go&s=8XGcsCpAjQeoQiMFJFB3fOXRscSAKg-SvaY2zDKAiAs&e=>.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by iandunham** [comment]
To me this looks to behave correctly now. If you play around in the FTO locus you can find connections between BMI related phenotypes and IRX3 (and IRX5).

**Comment by elipapa** [comment]
great work 👍 works a lot better with key, multiple selection and a dropdown giving you options for the gene track. 

i think now that all genes are turned on it ends up meeting more my expectation as well. I am able in a couple of click to highlight the relation I know about.

the key is a nice addition and does help in interpreting. two comments on that though:
- the distinction between fine mapping and LD is almost impossible to discern. would a dropdown option work better?
- could "selected indirectly" become "connected" to simplify the key?

other potential improvements:
- clicking a selected element could remove the selection from filters.
- switch red and blue so that red is selection and blue is relatedness ?
- have some info about the selection in a UI element at the top

**Comment by mkarmona** [comment]
@peatroot you now have all genes incorporated in the gecko structure which comes back to your GraphQL client.
