### ISSUE TITLE
Gecko plot and table - filters

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#123]
The gecko plot currently supports restriction to a set of selected entities (by clicking).

Following brief discussion with @andrewhercules, we think we should as a minimum for ASHG:
* add a filter row to the gecko table (beneath the column headers)
* add a slider filter for `overallScore` (G2V; this could live in the table only)
* add a toggle filter for finemapping

**Comment by peatroot** [comment]
Other thoughts on this welcome, @MayaGhoussaini @dj-wright @edm1 @emschmidt?

**Note**: The API does not currently return the G2V sources or tissue breakdown.

**Comment by elipapa** [comment]
should the filter for the overall score be quantile based?

**Comment by elipapa** [comment]
I would actually find more useful to filter the `studies` rather than the G2V connections. 
For instance:
- toggle display of uk biobank traits & gwas catalog traits
- `pval` filter slider to display only most significant studies
- `n_cases` filter slider to display only those studies with sufficient power.

**Comment by ElaineMcA** [comment]
Addressed in aggregated data.
