### ISSUE TITLE
Locus View table, view functional evidence column/button

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#174]
In the Locus View table, It is currently not obvious that to view functional (G2V) evidence for an evidence string you have to click on the tag variant.

One suggestion would be to have an additional column with a "view functional evidence" button, similar to:

![screen shot 2018-10-02 at 14 43 34](https://user-images.githubusercontent.com/1938268/46352454-b8360a00-c651-11e8-81e6-351de62ffd25.png)

**Comment by andrewhercules** [comment]
In an effort to remove the circular links found in the table, can we please do the following?

- Remove the links in the Lead Variant column
- Remove the links in the Gene column
- Remove the links in the Study column

This will give users a visual cue that they are to click to the Tag Variant column link based on our initial user journey. 

I do not suggest that we add another column with a separate button as the table is already wider than many screens due to a large number of columns and a lack of text wrapping in the Study Detail column - see #201

**Comment by andrewhercules** [comment]
Closing this ticket as it will be part of the work on building use cases for the locus plot
