### ISSUE TITLE
I would expect same icon going to the same page

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#205]
I would expect the same icon to go to the same page as it is confusing having two different buttons behaving the same but looking different.
![captura de pantalla -2018-10-09 11-48-42](https://user-images.githubusercontent.com/5394232/46664678-9260b600-cbb9-11e8-8002-0591d2d0a0b7.png)

![captura de pantalla -2018-10-09 11-51-07](https://user-images.githubusercontent.com/5394232/46664693-a0163b80-cbb9-11e8-9d77-cccb1aaccf43.png)

**Comment by mirandaio** [comment]
@mkarmona the query string parameters in the URL are different, so, the links go to different versions of the locus page.

**Comment by mkarmona** [comment]
@mirandaio same page but different configuration. both buttons must show the same icon and slightly different message, which I personally think should be the same though.

**Comment by andrewhercules** [comment]
@mirandaio, as a short-term solution, can we please alter the variant page header so that it is line with the gene page header with a larger Locus View button (with icon)?

![screen shot 2018-11-16 at 12 52 42](https://user-images.githubusercontent.com/7490258/48622428-a8bf1600-e99e-11e8-9964-f7b28d8ed85e.png)

@ElaineMcA, once the short-term fix is implemented, this ticket can be closed. A broader "look & feel" ticket will be opened pending the PoC Platform project as we will want to harmonise the visual style and framework for both services.

**Comment by andrewhercules** [comment]
Issue closed as it will be addressed in #304
