### ISSUE TITLE
Locus plot: SHORT-TERM solution for dense regions display issue

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#239]
Background: The locus plot can ask for a lot of data, particularly in the MHC region (6:28,477,797–33,448,354), which is dense in genes.

At this point we are filtering these regions and returning no data at all, which impacts users when they search for some of their "favourite" genes.

Objective: Find a way to present some reduced level of data to the user in these cases

Solutions to be investigated first.  
We have IDed the problematic areas in current data.  Possible to use this info to resolve in short-term?

Options discussed in brief together on 02Nov2018:
(i) Pop up message to indicate if load time is ~10sec for dense regions (acceptable from user perspective)
OR
(ii) only display the table in this case
OR
(iii) Restrict amount of data to display smaller band

**Comment by peatroot** [comment]
All three options above would require substantial work from @mkarmona as well as front-end. The solution we currently have (no DB query made; show *Region too dense*) is preferable until we move to a new version of the locus plot which aggregates across tag variants.

**Reasons why the three suggestions above would be difficult:**
(i) Making the DB query for dense regions will heavily degrade performance for other users of the site.
(ii) The table is currently generated on the front-end, so requires the DB query. @mkarmona could build a paginated table query, so that only the table could be shown.
(iii) Allowing the DB query within dense regions, in the case of a narrow locus, will still draw massive amounts of data, since only the gene or tag variant or lead variant needs to be in the narrow locus. For a given *string*, the others could be outside.

**Comment by iandunham** [comment]
If you are adamant that this is the way to go, we need to enhance the information in the error message to include that 

a. we are aware this is a problem, and we apologise
b. briefly why it happens
c. we are actively working on a solution that will enable data to be shown i.e. the new version of the locus plot and some kind of estimate of when we will do that. 

Remember the data we are looking at has taken 10 years to generate, so waiting for a while is not a necessarily a big issue for these users

**Comment by peatroot** [comment]
I've just raised with @mkarmona and we'll put our heads together next week, when he's switched back to working on the genetics portal, to try to come up with a feasible alternative.

For reference, the current message is **Ouch! The region (<chr>:<start>-<end>) is too dense to be shown.**. Perhaps we can update it to **We are sorry but this region (<chr>:<start>-<end>) contains a lot of raw data. We are currently working on an update that will show an aggregation of the raw data (aggregating across the tag variants). We hope to have this ready by our next release in February 2019, so please try this region again soon.** Is that ok?

**Comment by deniseOme** [comment]
First user to report having come across a dense region was today by email.

As per the message, I'd like to suggest adding a sentence re. signing up to the Open Targets Genetics newsletter (https://opentargets.us17.list-manage.com/subscribe?u=d11d0467053c1d4b918eb8738&id=38f9f14944), so that users know when the issue is better dealt with (we need to remember to make this available via the newsletter, @andrewhercules).

And I'd have a shorter message, without much detail (for example, 'raw data', "tag variants") as we may have naive users exploring it for the first time and they may feel overwhelmed by the jargon.

-----
We are sorry but this region (chr:start-end) is very gene dense and contains a lot of data. We are currently working on how to aggregate some of this data and hope to have this ready by our next release in February 2019. To be the first to know when this is addressed, please sign up to our newsletter.
-----

**Comment by ElaineMcA** [comment]
Timeline for next release pushed to Mar 2019 - based upon prioritisation meeting/ capacity review yesterday.

**Comment by ElaineMcA** [comment]
Message updated by FE, requires BE resource (once available) to push change to production.

**Comment by deniseOme** [comment]
Thanks @ElaineMcA, we had another user (this time from Biogen) reporting this shortcoming.

**Comment by ElaineMcA** [comment]
@mkarmona to address w/c 14Jan2019.

**Comment by ElaineMcA** [comment]
FE meeting 09Jan2019:

- [ ] Updated agreed message will be pushed to production **11 Jan2019**

- [ ] Cache transformation @ BE for specific dense loci - what time would this approach save? 
- Technical meeting to discuss the level of effort for option below as we have a list of dense regions.

Possible options for short-term technical discussion: 
- display +/-250KB only (default query is +/- to 2MB window) only to reduce data, maintain interaction knowing that full data remains in the data table.
- present message explaining restricted view above
- switch off functionality and interaction only if necessary

NEED to regroup before DECISION.

**Comment by andrewhercules** [comment]
As part of the short-term solution, we can also implement the waiting widget design pattern if there is still considerable data to process with the window reduced to +/-250KB, which would result in a delay to the user seeing the visualisation and data table.

![after-search-step-1-skeleton](https://user-images.githubusercontent.com/7490258/50959083-090f9700-14ba-11e9-978d-4b56744eb6eb.png)

**Comment by peatroot** [comment]
Tested the following locally with help of @mkarmona:
* locally re-enabled querying in dense regions (disabled in production)
* browsed to a 250 kb window (which is half the reduction proposed in last meeting)

Observed:
* API call takes about 10s
* browser then freezes and remains unresponsive (waited 5 minutes)

Propose that we leave the updated message in place and start to work changes to support the aggregated data that @edm1 has been preparing. I believe the data is ready and will shortly be put in the back-end. This should resolve the data magnitude issue, since it aggregates across tag variants.

**Comment by peatroot** [comment]
The dense location, for reference, was `6:31,000,000-31,250,000`.

**Comment by ElaineMcA** [comment]
Closing short-term issue.  Further follow-up will be detailed in  #256
