### ISSUE TITLE
should we limit v2g evidence to protein_coding genes only?

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#35]
currently we limit pchic to protein_coding gene only, but don't necessarily apply the same filters to other datasets.

**Comment by iandunham** [comment]
Do we know how many signals we get form the other data to non protein coding genes?

**Comment by edm1** [comment]
Ian advocates not including non-protein-coding genes for now.

There are many many more non-coding RNAs than protein-coding genes meaning that nearly all assignments will go to ncRNA.

**Comment by mkarmona** [comment]
@iandunham @edm1 May I suggest a configurable way of excluding / including a specific list of biotypes instead of sticking with a drastic filtering to just a hardcoded `protein_coding` ones? We already implement a similar [approach for the platform](https://github.com/opentargets/data_pipeline/blob/master/mrtarget.data.yml#L83)

**Comment by mkarmona** [comment]
[approach for the platform](url)

**Comment by mkarmona** [comment]
List of selectable biotypes
```
"3prime_overlapping_ncrna"
"antisense"
"IG_C_gene"
"IG_C_pseudogene"
"IG_D_gene"
"IG_J_gene"
"IG_J_pseudogene"
"IG_V_gene"
"IG_V_pseudogene"
"lincRNA"
"miRNA"
"misc_RNA"
"Mt_rRNA"
"Mt_tRNA"
"polymorphic_pseudogene"
"processed_transcript"
"protein_coding"
"pseudogene"
"rRNA"
"sense_intronic"
"sense_overlapping"
"snoRNA"
"snRNA"
"TR_C_gene"
"TR_D_gene"
"TR_J_gene"
"TR_J_pseudogene"
"TR_V_gene"
"TR_V_pseudogene"
```
