### ISSUE TITLE
Missing associated loci

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/genetics#424]
There are multiple studies in the public OTG portal that are missing independent loci. 
For example:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/7324184/80195965-f2447380-861c-11ea-9d28-db92e5d36c31.png">

Both studies display 3 and 1 associated loci respectively but both of the studies are empty:
https://genetics.opentargets.org/study/GCST005547
https://genetics.opentargets.org/study/GCST002190

**Comment by mkarmona** [comment]
@BjornWouters thanks. I will have a look at it too. We are also investigating the [other issue](https://github.com/opentargets/genetics/issues/422) you already opened.

**Comment by d0choa** [comment]
I'm revisiting this long-standing ticket. In both cases, we have the associations in the `toploci` table but we drop them as part of the data joining process.

Speculating about the possible causes of dropping these associations, it looks like in the case of study `GCST005547`, none of the associations have a beta or odds ratio value which might have caused the association the problem.

```
>>> toploci = spark.read.parquet("gs://genetics-portal-dev-staging/v2d/220210/toploci_betas_fixed.parquet")
>>> toploci.filter(F.col("study_id") == "GCST005547").show()
+----------+-----+--------+---+---+---------+----+-------------+-------------+----------+--------------+--------------+-------------+-------------+
|  study_id|chrom|     pos|ref|alt|direction|beta|beta_ci_lower|beta_ci_upper|odds_ratio|oddsr_ci_lower|oddsr_ci_upper|pval_mantissa|pval_exponent|
+----------+-----+--------+---+---+---------+----+-------------+-------------+----------+--------------+--------------+-------------+-------------+
|GCST005547|   11| 1226857|  G|  A|     null|null|         null|         null|      null|          null|          null|          2.0|           -9|
|GCST005547|   19|55320451|  C|  T|     null|null|         null|         null|      null|          null|          null|          5.0|          -11|
|GCST005547|   22|44859739|  A|  C|     null|null|         null|         null|      null|          null|          null|          3.0|          -10|
+----------+-----+--------+---+---+---------+----+-------------+-------------+----------+--------------+--------------+-------------+-------------+
```

The case for `GCST002190` is more puzzling. Information seems to be correct in the `toploci` input table and the variant is available in our variant-index. 

```
>>> toploci.filter(F.col("study_id") == "GCST002190").show()
+----------+-----+---------+---+---+---------+----+-------------+-------------+------------------+------------------+------------------+-------------+-------------+
|  study_id|chrom|      pos|ref|alt|direction|beta|beta_ci_lower|beta_ci_upper|        odds_ratio|    oddsr_ci_lower|    oddsr_ci_upper|pval_mantissa|pval_exponent|
+----------+-----+---------+---+---+---------+----+-------------+-------------+------------------+------------------+------------------+-------------+-------------+
|GCST002190|    X|153942092|  A|  G|        -|null|         null|         null|0.7616146230007617|0.6910664484832113|0.8393647748949921|          4.0|           -8|
+----------+-----+---------+---+---+---------+----+-------------+-------------+------------------+------------------+------------------+-------------+-------------+
```

I will however start a separate ticket to identify all missing top loci across the entire genetics portal, as I would anticipate different reasons for dropping such signals. Knowing the magnitude of the different issues will help us prioritise tasks in order to rescue these and other potential missing signals

**Comment by d0choa** [comment]
As described in #540 I can confirm the problem with both studies is that the top loci were dropped because they were not found in the LD expansion dataset
