### ISSUE TITLE
studies dropped for current release

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/genetics#444]
to be expanded

**Comment by xyg123** [comment]
FINNGEN_R5_AB1_CHOLERA
FINNGEN_R5_AB1_SCABIES
GCST90013791
FINNGEN_R5_R18_SENILITY
FINNGEN_R5_R18_FASCICULATION
FINNGEN_R5_K11_CROSSBITE
FINNGEN_R5_H7_BULLKERATOPATHY
FINNGEN_R5_R18_SOMNOLENCE
FINNGEN_R5_K11_OVERJET
FINNGEN_R5_AB1_TULARAEMIA
FINNGEN_R5_AB1_OTHER_SEPSIS
FINNGEN_R5_I9_HEARTFAIL_AND_CHD
FINNGEN_R5_AB1_SEPSIS
FINNGEN_R5_Q17_ANKYLOGLOSSIA
FINNGEN_R5_M13_ARTHROSIS_INCLAVO

**Comment by Jeremy37** [comment]
The FinnGen studies above aren't in the FinnGen manifest (https://r5.finngen.fi/api/phenos), so I dropped them from fine-mapping. Since we don't have study details for them, I think it's fine to just drop them.
On the other hand, the study GCST90013791 is a pre-published one from John Todd that we were hoping to include. So it's not in the main GWAS catalog yet, but the data are public under prepublished studies (https://www.ebi.ac.uk/gwas/downloads/summary-statistics).
If we need to get some study details for this one, perhaps it can be done manually?

**Comment by iandunham** [comment]
I would like GCST90013791 to be included if possible, please

**Comment by ktsirigos** [comment]
work completed
