### ISSUE TITLE
Credible set visualisation error on particular study

### ISSUE THREAD

**Issue by d0choa** [opentargets/genetics#466]
Looking at this study-locus page:
https://dev--genetics-app.netlify.app/study-locus/FINNGEN_R5_L12_ATOPIC/12_68255353_T_C

The credible set Manhattan of the second GWAS `Dermatitis and eczema (FINNGEN_R5, 2018)` fails to draw, producing the next (I believe d3) error:

```
[Error] Error: Invalid value for <line> attribute y1="NaN"
[Error] Error: Invalid value for <line> attribute y2="NaN"
```

We might want to use this page in blog posts etc.

<img width="769" alt="Screenshot 2021-06-17 at 21 19 25" src="https://user-images.githubusercontent.com/5097586/122466918-c9fe9d80-cfb1-11eb-95f5-a8494bb187e4.png">

**Comment by mirandaio** [comment]
The reason that there's no data for that region is because there's no data coming from the API. Here's the [query](https://open-targets-genetics-dev.ew.r.appspot.com/graphql/browser?query=query%20GWASRegionalQuery(%0A%20%20%24studyId%3A%20String!%0A%20%20%24chromosome%3A%20String!%0A%20%20%24start%3A%20Long!%0A%20%20%24end%3A%20Long!%0A)%20%7B%0A%20%20regional%3A%20gwasRegional(%0A%20%20%20%20studyId%3A%20%24studyId%0A%20%20%20%20chromosome%3A%20%24chromosome%0A%20%20%20%20start%3A%20%24start%0A%20%20%20%20end%3A%20%24end%0A%20%20)%20%7B%0A%20%20%20%20variant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%7D%0A%7D%0A&operationName=GWASRegionalQuery&variables=%7B%0A%20%20%22studyId%22%3A%20%22FINNGEN_R5_L12_DERMATITISECZEMA%22%2C%0A%20%20%22chromosome%22%3A%20%2212%22%2C%0A%20%20%22start%22%3A%2068005353%2C%0A%20%20%22end%22%3A%2068505353%0A%7D) that fetches the data.

**Comment by d0choa** [comment]
I found an equivalent case in production vs dev, for an old study:

https://genetics.opentargets.org/study-locus/GCST002222/19_44886339_G_A

<img width="764" alt="Screenshot 2021-06-22 at 09 49 40" src="https://user-images.githubusercontent.com/5097586/122894585-3c1f0b80-d33f-11eb-85f7-eb24f4c0ee3b.png">

https://dev--genetics-app.netlify.app/study-locus/GCST002222/19_44886339_G_A

<img width="762" alt="Screenshot 2021-06-22 at 09 50 32" src="https://user-images.githubusercontent.com/5097586/122894705-5658e980-d33f-11eb-8262-1baa5de013d1.png">

**Comment by mkarmona** [comment]
@d0choa @mirandaio fixed. There was a problem loading the gwas sa table with the filtered pval hits and therefore some data to show when colocalised were missing in the region
![image](https://user-images.githubusercontent.com/5394232/123060719-e7dd5f80-d402-11eb-9aa1-7ba75239305a.png)
