### ISSUE TITLE
The most promising pQTL associations from Sun et al. are missing in the V2G table 

### ISSUE THREAD

**Issue by MayaGhoussaini** [opentargets/genetics#469]
This could be a Front End issue but we need to investigate why lead pQTLs are still missing in the V2G table (especially the most significant ones e.g p-val<E-385). One example is the following: 
rs2127870 and FUT8 gene (p-value =9.8 E-396)

**Comment by mkarmona** [comment]
Solved. @MayaGhoussaini The problem comes from raw eQTL data where some p-values are smaller than the smallest positive number for a Double type then there is an exception somewhere and then overflowed to 0. I reverted the effect assuming all 0s have not null beta so I assign the smallest positive number for a Double type for that p-value. It will come fixed in the next iteration
