### ISSUE TITLE
Locus page shows nothing when accessed from “compare studies” page

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/genetics#503]
For example, search for the study “Marioni”, and then click the Compare Studies button, and choose to compare with “Jansen”. Click one of the Locus Plot buttons in the list below.

The Locus Plot page shows the error “A study ID needs a lead variant too”
E.g.:
https://main--genetics-app.netlify.app/locus?chromosome=1&end=208612944&selectedStudies=GCST005922&selectedStudies=GCST007320&start=206612944

**Comment by andrewhercules** [comment]
@carcruz can we please remove the locus plot button from the compare studies page? The button is found in the [ManhattansVariantsTable.js file](https://github.com/opentargets/genetics-app/blob/main/src/components/ManhattansVariantsTable.js).

Similarly, can we also remove the locus plot button from the [PheWASTable.js file](https://github.com/opentargets/genetics-app/blob/main/src/components/PheWASTable.js)? This button can be removed as it is the same button found at the top of the variant page.

**Comment by MayaGhoussaini** [comment]
@carcruz, I'm personally happy for the "locus plot" button to be removed from the PheWAS table as it is redundant (already covered by the button at the top of the page). 
Regarding removing the locus plot button from the compare studies page, I'm not against this especially in the current state of the locus plot page. The initial aim for this visualisation was to enable users when comparing different GWAS (2 or more) to see where the overlapping tag variants sit in the context of the genes nearby. If we remove this button for the time being, users can still access the list of overlapping SNPs but won't see the genes in the region in a single glimpse and where they are relative to the variant. I think we can remove it for now but we can come back to it in the future once we've refined the purpose of the Locus plot page (e.g. showing the genes implicated via L2G rather than V2G)

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `v6` release
